### ISSUE TITLE
nodejs child_process.spawn: no progress bar output

### ISSUE THREAD

**Issue by gtamas** [tj/node-progress#107]
The progress bar works totally fine when I run my node script like  this:

```
node somefile -c someconfig
```

However, if I do the same with .spawn(), the task works, but I don't see any progress bar output.

My task prints things to the console via Winston logger's console transport.

Here is what I see:

```
node tasks/users_1.js --config config.local
Warning!>Warning! This will drop all user data! Are you sure?> y
info: Dropped users..
info: Processing 93647 records..
info: 
done
info: Processing xxxx meta key, found 93640 records..
(progress bar should be here)
```

**Comment by jrouleau** [comment]
Are you piping the child's stderr to the parent? See: https://nodejs.org/api/child_process.html#child_process_child_stderr

**Comment by gtamas** [comment]
Yeah, thx. It works with the right options.. Sorry this was my mistake.

**Comment by onyx-nxt** [comment]
> Yeah, thx. It works with the right options.. Sorry this was my mistake.

What is your code? I am also facing this issue
