### ISSUE TITLE
Several new lines after progress bar

### ISSUE THREAD

**Issue by arjunkomath** [tj/node-progress#123]
As soon as progress bar starts lots of white space is there before the final log

![image](https://cloud.githubusercontent.com/assets/2555067/13723346/a148894e-e887-11e5-9cfb-a4c130988fae.png)

Config:
```
var barOpts = {
		width: 50,
		total: fileSize
	};
var bar = new ProgressBar(' Uploading [:bar] :percent :etas', barOpts);
```

Full Code: https://github.com/arjunkomath/Amazon-S3-CLI-Client/blob/master/index.js

**Comment by vesteraas** [comment]
I experienced this when I was generating ticks beyond the total for the progress bar.

**Comment by twang2218** [comment]
I got same problem, in my program, there are several TCP clients, and the number of new lines after the progress bar complete is based on how many clients. If there are 10 concurrent clients, there will be 10 new lines after the progress bar, and if there are 100 clients, there will be 100 new lines, which is very annoy.

```
✗ npm run simulator -- -h 192.168.99.100 -c 10 -n 100

> shui-device-server@0.3.0 simulator /Users/taowang/lab/shui-device/server
> node test/simulator.js "-h" "192.168.99.100" "-c" "10" "-n" "100"

info: Receiver Server: "192.168.99.100:7778"
info: Starting 10 devices for 100 requests...
  Sending requests [====================================================================================================]  100% 0.0s









info: Finished.
```

**Comment by twang2218** [comment]
I might locate the issue, the code in `/lib/node-progress.js` at [line 96](https://github.com/tj/node-progress/blob/master/lib/node-progress.js#L96)

```javascript
  // progress complete
  if (this.curr >= this.total) {
    if (this.renderThrottleTimeout) this.render();
    this.complete = true;
    this.terminate();
    this.callback(this);
    return;
  }
```

This part will call the `this.terminate()` no matter whether it's been called before. And the new line is coming from the `this.terminate()`:

```javascript
ProgressBar.prototype.terminate = function () {
  if (this.clear) {
    this.stream.clearLine();
    this.stream.cursorTo(0);
  } else this.stream.write('\n');
};
```

so, if the `bar.tick()` is called when the bar completed, which is quite common for some async calls, such as  setTimeout() or setInterval(), it will always write a new line. There should be some code to avoid multiple calls to `this.terminate()`.

The current workaround is that manually checking whether the progress is finished or not, and avoid call `bar.tick()` if the progress is finished already. A single new line may be manually added depends on the case.

**Comment by arjunkomath** [comment]
I had the same issue, `bar.tick()` was being called even after the progress is finished. Fixed it 👍 
Thanks!
