### ISSUE TITLE
Is there a way to mute the bar?

### ISSUE THREAD

**Issue by jfoclpf** [tj/node-progress#188]
How do you verbose debug variables and conciliate with a progress bar?
I do not want a progress bar polluting my [debug](https://www.npmjs.com/package/debug) mode

I use this

```js
const debug = require('debug')('build')
var Bar = debug.enabled
  ? { tick: function () {} }
  : new ProgressBar('[:bar] :percent :file', { total: getNuberOfTotalFiles(), width: 80 })
```

What do you think? Is there any simple function to mute the bar?

Thanks for the great project

**Comment by gkostov** [comment]
If you use the `.interrupt("debug some stuff")` method it will print that just as you would see it without the bar but will still keep the bar at the bottom of the screen. Like"

> debug val1: 52
> debug val32: 44
> debug something
> debug some stuff
> [==---------------] 10%

This should look good enough unless you're outputting to something that's not a TTY.
