### ISSUE TITLE
Buffering updates

### ISSUE THREAD

**Issue by zxlin** [tj/node-progress#194]
Would it make sense to buffer the redraws to some minimum threshold such that updates are not redrawn faster than the human eye can comprehend such that it would reduce data overhead (for remote servers) and reduce stress on CPU to redraw so quickly. 

If there's decent interest from the community and maintainers, I can work on a PR for this.

**Comment by prantlf** [comment]
Yes, some throttling would be nice. For example, the shortest update interval in milliseconds:

```js
// Update the console not more often, than once per second
updateThrottling: 1000
```

A workaround forcing a display update only when crossing a one-percent boundary:

```js
let receivedBytes = 0
let lastPercent
showProgress = (currentBytes, totalBytes) => {
  const currentPercent = Math.round(currentBytes / totalBytes * 100)
  if (lastPercent !== currentPercent) {
    bar.tick(currentBytes - receivedBytes)
    receivedBytes = currentBytes
    lastPercent = currentPercent
  }
}
browserFetcher.download(revision, showProgress)
```

**Comment by zxlin** [comment]
I went back and re-read the docs and there does appear to already be a setting for this `renderThrottle`.
