### ISSUE TITLE
Please continue tagging the released versions on Github so it's clear which version it corresponds to 

### ISSUE THREAD

**Issue by mohe2015** [tj/node-progress#213]
Hi,

would love if you could continue to tag the versions you release on npm also on Github. E.g. https://www.npmjs.com/package/progress/v/2.0.3 is not tagged

Kind regards
Moritz

**Comment by NathanPB** [comment]
I think it's abandoned

**Comment by mohe2015** [comment]
Probably but unfortunately it's in some pretty important packages as dependency. Well we all know the npm ecosystem is garbage.
