### ISSUE TITLE
Not working with Grunt

### ISSUE THREAD

**Issue by mhluska** [tj/node-progress#62]
The progress bar doesn't seem to show up when run with [grunt-shell](https://github.com/sindresorhus/grunt-shell). Any idea what is going on?

**Comment by hiulit** [comment]
Do you know any other grunt shell plugin that would work with node-progress? Thanks!

**Comment by hiulit** [comment]
Ok, I found a fork of this project that works with `grunt-shell`: https://github.com/crash83k/node-progress-3
